### PR TITLE
Update ESX

### PR DESCRIPTION
**Pull request by KalinkaGit**
Update server.lua to last ESX version.

### CODE REVIEW

**Comment by Richards0nd** [comment]
It's almost perfect.
He's just not identifying the player's license
In function:
```
function getPlayerID(source)
    local xplayer = ESX.GetPlayerFromId(source)
    local player = xplayer.identifier
    return player
end
```
Is returning as null or empty
I tried in several ways to return the player's license, but without success.

**Comment by maguhd** [comment]
> Update server.lua to last ESX version.

I did everything you said there....still dont get a phone number...and cant make phone calls and messages

I get this errors in the server console. 

https://prnt.sc/sdp12v

**Comment by dutchplayers** [comment]
Do this: ```
function getPlayerID(source)
	local license = GetPlayerIdentifiers(source)[2]
	local player = string.gsub(license, "license:", "")
    return player
end
```

**Comment by SidVicious99** [comment]
This update twitter still doesn't work.

can't grab the player id.

**Pull request closed without merging**
